---
title: "Assignment 1"
author: "Md Asaduzzaman"
date: "`r Sys.Date()`"
output: openintro::lab_report
---
```{r}
install.packages("tidyverse")
install.packages("ggthemes")
```

```{r load-packages, message=FALSE}
library(tidyverse)
```
 
 #read data from github
```{r}
poll_data = read.csv("https://raw.githubusercontent.com/asadny82/Data607/main/generic_ballot_polls.csv", header = TRUE,sep ="," )
 pollPar <- data.frame(poll_data$poll_id,poll_data$pollster_id,poll_data$pollster, poll_data$sponsor_ids,poll_data$sponsors,poll_data$dem,poll_data$rep,poll_data$pollster_rating_id,poll_data$transparency_score)
 colnames(pollPar)<-c("poll_id","pollster_id","pollster","transparency_score","pollster_rating_id","sponsor_ids","sponsors","dem","rep")
 pollPar

 
```
```{r pollster has high rating for dem}
pollDem_sub <- subset(pollPar, dem>rep)
pollDem_sub<- pollDem_sub[,c("poll_id","pollster_id","pollster","transparency_score","sponsor_ids","sponsors","pollster_rating_id")]
pollDem_sub

```
```{r pollster has snonser}
pollPar_sub <- subset(pollPar, sponsor_ids < 0)
pollPar_sub <- pollPar_sub[,c("poll_id","pollster_id","pollster","sponsor_ids","sponsors","pollster_rating_id")]
pollPar_sub

```
 #pollsert has high rating for rep
 
```{r}
pollRep_sub <- subset(pollPar, rep>dem)
pollRep_sub<- pollRep_sub[,c("poll_id","pollster_id","pollster","sponsor_ids","sponsors","pollster_rating_id")]
pollRep_sub
```
 
 
```{r}
TopTRansScore <-head(arrange(pollPar,poll_data$'transparency_score',decreasing = TRUE),n=50)
TopTRansScore <-TopTRansScore[,c("dem","rep","transparency_score")]
TopTRansScore
```
 
 
 
```{r}
 TomScoregg <- ggplot(NULL, aes(x, y)) + 
  geom_line(data=TopTRansScore , aes(x=transparency_score, y=dem, group=1), col="blue") +
  geom_line(data=TopTRansScore , aes(x=transparency_score, y=rep, group=1), col="red")
   
TomScoregg
```
Conclusion: Dem has grater transparency_score than rep base on top 50 transparency_score. 
